---
tags:
  - 代码
---
程序运行一出现错误，就导致整个系统崩溃。
如果程序员认为一段代码可能出现异常，可以进行异常处理，保证程序的健壮性，让异常不会让程序中断。


## 概述

在java中，程序执行中发生的不正常情况称为“异常”。（开发中的语法错误和逻辑错误不能称为异常）

异常分为两类：
- **Error（错误）**：jvm无法解决的严重问题，如jvm系统内部错误、资源耗尽等严重情况，会导致程序崩溃。
- **Exception**：其他因编程错误或偶然的外在因素导致的一般性问题。可以使用针对性的代码进行处理，例如空指针访问、试图读取不存在的文件、网络连接中断等。Exception分为两大类：运行时异常和编译时异常（编程时报错）。![[Screenshot 2024-10-06 112537.png]]

运行时异常不一定要处理，因为太普遍了，全处理会影响程序的可读性和运行效率。



---
## 五大运行时异常

1. NullPointerException 空指针异常：当程序试图在需要对象的地方使用null时，抛出该异常。
2. ArithmeticException 数学运算异常：出现异常的运算条件式抛出异常。
3. ArrayIndexOutOfBoundsException 数组下标越界异常：用非法索引访问数组时抛出异常。
4. ClassCastException 类型转换异常：当试图将对象强制转换为不是实例的子类时抛出异常。
5. NumberFormatException 数字格式不正确异常：当程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常。


---
## 编译异常

常见的编译异常：
1. SQLException 操作数据库时，查询表可能发生的异常。
2. IOException 操作文件时，发生的异常。
3. FileNotFoundException 操作一个不存在的文件发生异常。
4. ClassNotFoundException 加载不存在的类发生异常。
5. EOFException 操作文件，到文件末尾发生异常。
6. IllegalArguementException 参数异常。


---
## 异常处理

### >try-catch-finally

try{
	代码可能有异常。
} catch (Exception e ){
	捕获异常，将异常封装成Exception类型，传递给catch。
	得到异常后程序员自行编写处理。
	如果没有异常，catch代码块不执行。
} finally{
	不管try代码块是否发生异常，都会执行finally代码块。
	通常资源释放的代码会放在finally代码块中。
}

try中有多个异常时，catch只会捕获首个异常，可以通过多个catch来处理不同类型的异常，但只有首个异常会被处理。**子类异常要写在父类异常前面**。
```java
int num1 = 10;
int num2 = 0;
String str = null;
try {
	int result = num1 / num2;
	System.out.println(str.length());
} catch (ArithmeticException e) {
	System.out.println("ArithmeticException");
} catch (NullPointerException e) {
	System.out.println("NullPointerException");
} catch (Exception e) {
	System.out.println(e.toString());
}//只会输出ArithmeticException
```

try-finally，没有捕获异常，异常程序会崩溃，但是在崩溃前会执行finally的代码。
```java
try{

}finally{

}
```


### >throws

把异常抛给调用者，若调用者没有处理，再往上抛，最终只能到JVM，JVM会直接打印异常信息并中断程序。

如果不使用try-catch，默认会使用throws方法。

throws后面的异常类型可以是方法中的异常类型，也可以是它的父类。
```java
public void f() throws Exception{};
```

细节：
- 编译异常程序必须处理。
- 运行时异常，程序没有处理则默认throws方式处理。
- 子类重写父类的方法时，子类重写的方法，所抛出的异常类型要么与父类抛出的异常类型一致，要么时父类抛出异常的子类型。
- 在throws中，如果有方法try-catch，就相当于异常处理，不必再throws。


---
## 自定义异常 throw

自定义异常步骤：
1. 定义类：自定义异常类名，继承Exception或者RuntimException。
2. 如果继承Exception，则属于编译异常。
3. 如果继承RuntimeException，则属于运行异常。
（一般继承RuntimeException）
4. 使用时用throw 异常对象。
```java
class AgeException extends RuntimeException{
    public AgeException(String message) {
        super(message);//错误信息将传给超类的Throwable方法
    }
}

int age = 880;
if (!(age >= 18 && age <= 120)) {
	throw new AgeException("年龄必须在18-120之间");
}
```

当然throw可以抛出已有的异常类，在try-catch的try代码块中如果使用throw，则立刻中断try代码的运行，进入到catch。
```java
try{
	throw ArithmeticException("运算有误");
	System.out.print("不再输出")
} catch(ArithmeticException e){
	System.out.print(e.getMessage());//输出运算有误
}//“不再输出”将不会执行
```